### ISSUE TITLE
Error on +snippet/edit

### ISSUE THREAD

**Issue by Janfel** [doomemacs/doomemacs#4127]
**What actually happened?**
Calling `+snippet/edit` interactively on some snippets throws an error. Backtrace below.

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  aref(nil 6)
  (progn (aref template 6))
  (progn (progn (aref template 6)))
  (let* ((major-mode (if (eq major-mode 'snippet-mode) (intern (file-name-base (directory-file-name default-directory))) major-mode)) (template (yas--get-template-by-uuid major-mode template-uuid)) (template-path (progn (progn (aref template 6))))) (if (file-in-directory-p template-path +snippets-dir) (find-file template-path) (let ((buf (get-buffer-create (format "*%s*" (file-name-nondirectory template-path))))) (save-current-buffer (set-buffer (switch-to-buffer buf)) (insert-file-contents template-path) (snippet-mode) (setq default-directory (expand-file-name (file-name-nondirectory template-path) (expand-file-name (symbol-name major-mode) +snippets-dir)))))))
  +snippets/edit("comment")
  #<subr funcall-interactively>(+snippets/edit "comment")
  apply(#<subr funcall-interactively> (+snippets/edit "comment"))
  funcall-interactively(+snippets/edit "comment")
  #<subr call-interactively>(+snippets/edit nil nil)
  apply(#<subr call-interactively> (+snippets/edit nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> +snippets/edit nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (+snippets/edit nil nil))
  call-interactively(+snippets/edit nil nil)
  command-execute(+snippets/edit)
</pre></details>

**Steps to reproduce:**
1. Open a new `emacs-lisp-mode` buffer.
2. Call `+snippets/edit` (e.g. `C-c & C-v`).
3. Choose snippet `yn` (for `y-or-n-p`).

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64
	path       (~/bin ~/opt/bin /usr/local/bin /usr/bin ~/.local/bin /usr/local/sbin /usr/lib/jvm/default/bin ~/.dotnet/tools ~/var/go/bin ~/.local/share/cabal/bin ~/opt/ghcup/bin ~/.gem/ruby/2.7.0 ~/.local/share/cargo/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/opt/doom-emacs/
	version    27.1
	build      Aug 28, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.config/doom-emacs/
	version    2.0.9
	build      HEAD -> develop ff6699e79 2020-10-21 12:04:52 -0400
	elc-files  0
	modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (&user fmt +define) rotate-text snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit make :lang data emacs-lisp markdown org sh yaml (&user arduino) (&user basic) (cc +lsp) clojure common-lisp elixir (&user fennel) (haskell +dante) latex (lua +moonscript) (python +lsp) (rust +lsp) scheme :config (&user literate) (default +evil +bindings +smartparens))
	packages   ((meson-mode) (moonscript :pin ac5d35d3a1970db958c687991a1f2c49f7921150 :recipe (:fork (:host github :repo Janfel/moonscript-mode))) (php-mode) (rustic :pin ee541d6247b48e1cc103eee8f8e7d93c88fb0a2a) (async) (flycheck-clang-tidy) (evil-escape :disable t) (evil-matchit) (form-feed) (highlight-indent-guides) (hungry-delete) (company-quickhelp) (company-jedi))
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 5d5d94d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by czikus** [comment]
Unfortunately, the issue is not resolved for me. I'm seeing the exact same error, but I'm not using doom-snippets.

```
(wrong-type-argument arrayp nil)
  (aref nil 6)
  (progn (aref template 6))
  (progn (progn (aref template 6)))
  (let* ((major-mode (if (eq major-mode 'snippet-mode) (intern (file-name-base (directory-file-name default-directory))) major-mode)) (template (yas--get-template-by-uuid major-mode template-uuid)) (template-path (progn (progn (aref template 6))))) (if (file-in-directory-p template-path +snippets-dir) (find-file template-path) (let ((buf (get-buffer-create (format "*%s*" (file-name-nondirectory template-path))))) (save-current-buffer (set-buffer (switch-to-buffer buf)) (insert-file-contents template-path) (snippet-mode) (setq default-directory (expand-file-name (file-name-nondirectory template-path) (expand-file-name (symbol-name major-mode) +snippets-dir)))))))
```

**Comment by hlissner** [comment]
@czikus 523ced6 should fix the issue.

**Comment by czikus** [comment]
@hlissner The error is indeed gone, but now instead of a snippet buffer, I'm only seeing a message "Couldn’t find a snippet with uuid nil".

**Comment by hlissner** [comment]
@czikus Sounds like you're selecting a snippet that has no (or a blank) `uuid:`. Can you link to what snippet library you're using and what snippet you're trying to edit?

**Comment by czikus** [comment]
The snippet does have non-blank uuid:
```
# -*- mode: snippet -*-
# name: figure
# key: fig
# uuid: fig
# --
#+caption: ${1:caption}
#+attr_latex: ${2:scale=0.75}
#+label: fig:${3:label}
```

and I noticed that `(+snippets/edit "fig")` works great when run non-interactively. I get the error when I run it as an interactive command. The reason seems to be that `(+snippet--completing-read-uuid "Select snippet to alias: "                                     current-prefix-arg)` always returns nil for any snippet.

**Comment by hlissner** [comment]
Odd. I can't reproduce that, neither with that snippet. What's the output of

```elisp
(cl-loop for (_ . tpl) in (mapcan #'yas--table-templates (yas--get-snippet-tables))
         for txt = (format "%-25s%-30s%s"
                           (yas--template-key tpl)
                           (yas--template-name tpl)
                           (abbreviate-file-name (yas--template-load-file tpl)))
         collect
         (progn
           (set-text-properties
            0 (length txt)
            `(uuid ,(yas--template-uuid tpl) path ,(yas--template-load-file tpl))
            txt)
           txt))
```

**Comment by hlissner** [comment]
Ah, nevermind. I can reproduce this with `helm`, but not `ivy`. That would explain it. I'll see if I can find a fix.

**Comment by czikus** [comment]
Yes, I forgot to mention that I'm using helm. Thanks for looking into this.

**Comment by jkroes** [comment]
Same experience as @dileep-kishore here.

**Comment by jgrey4296** [comment]
This issue with this is helm strips text properties off its returned values (see [this issue](https://github.com/emacs-helm/helm/issues/2453))

The recommended solution is to add a custom helm handler for `+snippet-completing-read-uuid` to `helm-completing-read-handlers-alist` but thats overkill. 

Instead, I quickly refactored `+snippet--completing-read-uuid` as below to create an alist of (snippet-info-string . uuid)'s,
and return the uuid from looking in that.
```
(defun +snippet--completing-read-uuid (prompt all-snippets &rest args)
  (let* ((snippet-data (cl-loop for (_ . tpl) in (mapcan #'yas--table-templates (if all-snippets
                                                                                   (hash-table-values yas--tables)
                                                                                 (yas--get-snippet-tables)))

                               for txt = (format "%-25s%-30s%s"
                                                 (yas--template-key tpl)
                                                 (yas--template-name tpl)
                                                 (abbreviate-file-name (yas--template-load-file tpl)))
                               collect
                               `(,txt . ,(yas--template-uuid tpl))))
        (selected-value (apply #'completing-read prompt snippet-data args)))
  (alist-get selected-value snippet-data nil nil 'equal)))
```

**Comment by theutz** [comment]
I'm also having this same experience using vertico. :(

**Comment by Khoulaiz** [comment]
I have the same problem with vertico. Your above refactored code works for me and fixes the problem.
