### ISSUE TITLE
LaTeX/evil -- SPC not inserting whitespace

### ISSUE THREAD

**Issue by wuqui** [doomemacs/doomemacs#4762]
**What did you expect to happen?**
Being in `latex`mode and in insert mode, hitting the space key should insert whitespace.

**What actually happened?**
Hitting `SPC` triggers command mode. I cannot insert any whitespace anymore. As soon as I switch to `org-mode`, everything works again and `SPC` in insert mode just adds whitespace, not acting like the leader key.

This probably sounds like a problem with my config, but I can't identify any problems there. I've also moved my config (`config.el` and `config.org`) out of the way and I still get the same problematic behaviour.

**System information:**
<del>`doom-info` produces an error message for me, both if called from within inside Emacs as well as from the shell (https://pastebin.com/pzrUKwTH). Apart from that, everything works fine and `doom doctor` doesn't suggest any problems either. </del>

https://pastebin.com/AuhgN70x

**Comment by hlissner** [comment]
Please update Doom, then include your `M-x doom/info`, and see if your issue is still present.

**Comment by wuqui** [comment]
Thanks a lot for looking into this! 😊 

> Please update Doom, then include your `M-x doom/info`, and see if your issue is still present.

It's up-to-date, but `M-x doom/info` still produces an error. Here's the debugger info:

```
Debugger entered--Lisp error: (wrong-type-argument listp unpin)
  car(unpin)
  (format (concat "%11s  %s\n") (car spec) (if (listp (cdr spec)) (mapconcat #'(lambda (x) (format "%s" x)) (cdr spec) " ") (cdr spec)))
  (doom--format (format (concat "%11s  %s\n") (car spec) (if (listp (cdr spec)) (mapconcat #'(lambda (x) (format "%s" x)) (cdr spec) " ") (cdr spec))))
  (insert (doom--format (format (concat "%11s  %s\n") (car spec) (if (listp (cdr spec)) (mapconcat #'(lambda (x) (format "%s" x)) (cdr spec) " ") (cdr spec)))))
  (let ((spec (car --dolist-tail--))) (insert (doom--format (format (concat "%11s  %s\n") (car spec) (if (listp (cdr spec)) (mapconcat #'(lambda ... ...) (cdr spec) " ") (cdr spec))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((spec (car --dolist-tail--))) (insert (doom--format (format (concat "%11s  %s\n") (car spec) (if (listp (cdr spec)) (mapconcat #'... (cdr spec) " ") (cdr spec))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- info)) (while --dolist-tail-- (let ((spec (car --dolist-tail--))) (insert (doom--format (format (concat "%11s  %s\n") (car spec) (if (listp ...) (mapconcat ... ... " ") (cdr spec))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (if raw (progn (save-excursion (pp info (current-buffer))) (let ((--dolist-tail-- '(modules packages))) (while --dolist-tail-- (let ((sym (car --dolist-tail--))) (if (re-search-forward (format "^ *\\((%s\\)" sym) nil t) (progn (goto-char ...) (let* ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((--dolist-tail-- info)) (while --dolist-tail-- (let ((spec (car --dolist-tail--))) (insert (doom--format (format (concat "%11s  %s\n") (car spec) (if ... ... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (save-current-buffer (set-buffer buffer) (erase-buffer) (if raw (progn (save-excursion (pp info (current-buffer))) (let ((--dolist-tail-- '(modules packages))) (while --dolist-tail-- (let ((sym ...)) (if (re-search-forward ... nil t) (progn ... ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (let ((--dolist-tail-- info)) (while --dolist-tail-- (let ((spec (car --dolist-tail--))) (insert (doom--format (format ... ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (if (not doom-interactive-p) (doom--print (doom--format (format (buffer-string)))) (save-current-buffer (set-buffer (pop-to-buffer buffer)) (setq buffer-read-only t) (goto-char (point-min)) (kill-new (buffer-string)) (if (y-or-n-p "Your doom-info was copied to the clipboard.\n\nOpen ...") (progn (browse-url "https://pastebin.com"))))))
  (let ((buffer (get-buffer-create "*doom info*")) (info (doom-info))) (save-current-buffer (set-buffer buffer) (erase-buffer) (if raw (progn (save-excursion (pp info (current-buffer))) (let ((--dolist-tail-- '...)) (while --dolist-tail-- (let (...) (if ... ...) (setq --dolist-tail-- ...))))) (let ((--dolist-tail-- info)) (while --dolist-tail-- (let ((spec ...)) (insert (doom--format ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (if (not doom-interactive-p) (doom--print (doom--format (format (buffer-string)))) (save-current-buffer (set-buffer (pop-to-buffer buffer)) (setq buffer-read-only t) (goto-char (point-min)) (kill-new (buffer-string)) (if (y-or-n-p "Your doom-info was copied to the clipboard.\n\nOpen ...") (progn (browse-url "https://pastebin.com")))))))
  doom/info(nil)
  #<subr funcall-interactively>(doom/info nil)
  apply(#<subr funcall-interactively> (doom/info nil))
  funcall-interactively(doom/info nil)
  #<subr call-interactively>(doom/info record nil)
  apply(#<subr call-interactively> (doom/info record nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> doom/info record nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (doom/info record nil))
  call-interactively(doom/info record nil)
  command-execute(doom/info record)
  counsel-M-x-action("doom/info")
  funcall(counsel-M-x-action "doom/info")
  (if ivy-marked-candidates (ivy--call-marked action) (funcall action x))
  (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore))
  (prog1 (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore)) (if (or (eq ivy-exit 'done) (minibuffer-window-active-p (selected-window)) (null (active-minibuffer-window))) nil (select-window (active-minibuffer-window))))
  (cond ((null action) current) (t (select-window (ivy--get-window ivy-last)) (set-buffer (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 13))) (prog1 (unwind-protect (if ivy-marked-candidates (ivy--call-marked action) (funcall action x)) (ivy-recursive-restore)) (if (or (eq ivy-exit 'done) (minibuffer-window-active-p (selected-window)) (null (active-minibuffer-window))) nil (select-window (active-minibuffer-window))))))
  (let* ((action (if (functionp ivy-inhibit-action) ivy-inhibit-action (and (not ivy-inhibit-action) (ivy--get-action ivy-last)))) (current (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 23))) (x (ivy--call-cand current)) (res (cond ((null action) current) (t (select-window (ivy--get-window ivy-last)) (set-buffer (progn (or ... ...) (aref ivy-last 13))) (prog1 (unwind-protect (if ivy-marked-candidates ... ...) (ivy-recursive-restore)) (if (or ... ... ...) nil (select-window ...))))))) (if ivy-inhibit-action res current))
  ivy-call()
  (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not (window-minibuffer-p))) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil (let (...) (save-current-buffer ...))) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil (remove-hook 'minibuffer-setup-hook setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (let* ((hist ...) (minibuffer-completion-table collection) (minibuffer-completion-predicate predicate) (ivy-height ...) (resize-mini-windows ...)) (if (and ivy-auto-select-single-candidate ivy--all-candidates ...) (progn ... ...) (condition-case err ... ...)) (if (eq ivy-exit ...) (progn ...)))) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or (plist-get extra-props :session) (if (or ... ... ...) nil caller)))) (if session (progn (progn (or (and ... t) (signal ... ...)) (let* (...) (aset v 27 ...))) (ivy--alist-set 'ivy--sessions session ivy-last)))) (ivy--cleanup)) (ivy-call))
  (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not (window-minibuffer-p))) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil (let ... ...)) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil (remove-hook ... setup-hook) (funcall fun))) (unwind-protect (progn (add-hook 'minibuffer-setup-hook setup-hook) (let* (... ... ... ... ...) (if ... ... ...) (if ... ...))) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or (plist-get extra-props :session) (if ... nil caller)))) (if session (progn (progn (or ... ...) (let* ... ...)) (ivy--alist-set 'ivy--sessions session ivy-last)))) (ivy--cleanup)) (ivy-call)))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:predicate :require-match :initial-input :history :preselect :def :keymap :update-fn :sort :action :multi-action :unwind :re-builder :matcher :dynamic-collection :extra-props :caller :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :requir..." (car --cl-keys--)))))) (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last (not ...)) (progn (ivy-alist-setting ivy-display-functions-alist caller))))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn 'auto) #'(lambda nil ...) update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun #'ivy--minibuffer-setup) setup-hook) (setq setup-hook #'(lambda nil ... ...)) (unwind-protect (progn (add-hook ... setup-hook) (let* ... ... ...)) (remove-hook 'minibuffer-setup-hook setup-hook))) (let ((session (or ... ...))) (if session (progn (progn ... ...) (ivy--alist-set ... session ivy-last)))) (ivy--cleanup)) (ivy-call))))
  (let* ((predicate (car (cdr (plist-member --cl-rest-- ':predicate)))) (require-match (car (cdr (plist-member --cl-rest-- ':require-match)))) (initial-input (car (cdr (plist-member --cl-rest-- ':initial-input)))) (history (car (cdr (plist-member --cl-rest-- ':history)))) (preselect (car (cdr (plist-member --cl-rest-- ':preselect)))) (def (car (cdr (plist-member --cl-rest-- ':def)))) (keymap (car (cdr (plist-member --cl-rest-- ':keymap)))) (update-fn (car (cdr (plist-member --cl-rest-- ':update-fn)))) (sort (car (cdr (plist-member --cl-rest-- ':sort)))) (action (car (cdr (plist-member --cl-rest-- ':action)))) (multi-action (car (cdr (plist-member --cl-rest-- ':multi-action)))) (unwind (car (cdr (plist-member --cl-rest-- ':unwind)))) (re-builder (car (cdr (plist-member --cl-rest-- ':re-builder)))) (matcher (car (cdr (plist-member --cl-rest-- ':matcher)))) (dynamic-collection (car (cdr (plist-member --cl-rest-- ':dynamic-collection)))) (extra-props (car (cdr (plist-member --cl-rest-- ':extra-props)))) (caller (car (cdr (plist-member --cl-rest-- ':caller))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:predicate :requir..." (car --cl-keys--)))))) (progn (let ((init-fn (ivy-alist-setting ivy-init-fns-alist caller))) (if init-fn (progn (funcall init-fn)))) (if (equal overriding-local-map '(keymap)) (progn (keyboard-quit))) (setq caller (or caller this-command)) (let* ((ivy-recursive-last (and (active-minibuffer-window) ivy-last)) (ivy--display-function (if (or ivy-recursive-last ...) (progn ...)))) (setq update-fn (or update-fn (ivy-alist-setting ivy-update-fns-alist caller))) (setq unwind (or unwind (ivy-alist-setting ivy-unwind-fns-alist caller))) (setq ivy-last (make-ivy-state :prompt (ivy--update-prompt prompt) :collection collection :predicate predicate :require-match require-match :initial-input initial-input :history history :preselect preselect :keymap keymap :update-fn (if (eq update-fn ...) #'... update-fn) :sort sort :action (ivy--compute-extra-actions action caller) :multi-action multi-action :frame (selected-frame) :window (selected-window) :buffer (current-buffer) :unwind unwind :re-builder re-builder :matcher matcher :dynamic-collection dynamic-collection :display-transformer-fn (ivy-alist-setting ivy--display-transformers-alist caller) :directory default-directory :extra-props extra-props :caller caller :def def)) (ivy--reset-state ivy-last) (unwind-protect (let ((fun ...) setup-hook) (setq setup-hook #'...) (unwind-protect (progn ... ...) (remove-hook ... setup-hook))) (let ((session ...)) (if session (progn ... ...))) (ivy--cleanup)) (ivy-call)))))
  ivy-read("M-x " ("doom/info" "recover-file" "latex-mode" "org-mode" "conda-env-deactivate" "LaTeX-mode" "tex-mode" "q/repl-qitem" "mixed-pitch-mode" "conda-env-activate" "TeX-fold-mode" "treemacs-icons-dired-mode" "org-roam-db-build-cache" "run-ess-r" "query-replace" "jupyter-run-repl" "orb-insert" "run-python" "doom/reload" "markdown-mode" "q/repl-macros" "orb-note-actions" "q/repl-qenum" "anaconda-mode" "auto-insert-mode" "org-table-shrink" "pdf-tools-install" "org-roam-build-cache" "org-fancy-priorities-mode" "org-agenda-fontify-priorities" "clone-indirect-buffer-other-frame" "clone-indirect-buffer-other-window" "align" "org-ref" "lpr-buffer" "+evil:align" "helm-bibtex" "org-ref-helm" "q/repl-qblank" "conda-env-list" "org-beamer-mode" "yas-new-snippet" "org-roam-capture" "org-roam-find-file" "outline-minor-mode" "text-scale-decrease" "text-scale-increase" "doom/increase-font-size" "pdf-info-check-epdfinfo" "org-ref-open-bibtex-notes" ...) :predicate #f(compiled-function (x) #<bytecode 0x1fef414babd9>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  #<subr funcall-interactively>(counsel-M-x)
  apply(#<subr funcall-interactively> counsel-M-x)
  funcall-interactively(counsel-M-x)
  #<subr call-interactively>(counsel-M-x nil nil)
  apply(#<subr call-interactively> (counsel-M-x nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

> Also, please include any errors/warnings in *Messages* after opening an latex buffer. `SPC h e` or `C-h e` will open it.

Here's the output:

```
temp.tex has auto save data; consider M-x recover-this-file
Note: standard-indent, tab-width, evil-shift-width adjusted to 2
Applying style hooks...done
DOOM [ui/doom-dashboard] Changed dashboard’s PWD to /Users/quirin/temp/latex/
Garbage collecting...done (0.145s)
````

**Comment by HyunggyuJang** [comment]
I think this has to do with your `package.el` file. I experienced the same thing when I have used `unpin!` to install package. I believe this error should gone after remove all the code involving `unpin!` command in your private doom file, `package.el` where all `package!` related things should go.

**Comment by wuqui** [comment]
Thanks for jumping in and trying to help!

> I think this has to do with your `package.el` file. I experienced the same thing when I have used `unpin!` to install package. I believe this error should gone after remove all the code involving `unpin!` command in your private doom file, `package.el` where all `package!` related things should go.

I checked `packages.el` and I do indeed have two `unpin!` commands in it:

```
(package! treemacs-icons-dired)

(package! org-ref)

(package! ox-word
  :recipe (:host github
           :repo "jkitchin/scimax"
           :files ("ox-word.el")))

(package! org-transclusion
  :recipe (:host github
           :repo "nobiot/org-transclusion"
           :branch "main"
           :files ("org-transclusion.el")))

(package! dired-narrow)

(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex"))
;; When using org-roam via the `+roam` flag
;; (unpin! org-roam company-org-roam)
;; When using bibtex-completion via the `biblio` module
;; (unpin! bibtex-completion helm-bibtex ivy-bibtex)

(package! outline-magic
  :recipe (:host github
           :repo "tj64/outline-magic"))
```

I took these two `unpin!` lines from the recommended Doom configuration for `org-roam-bibtex` (https://github.com/org-roam/org-roam-bibtex). 

Unfortunately, commenting out these lines doesn't solve the problem, however.

**Comment by hlissner** [comment]
@wuqui `doom/info` issues are now resolved in abec86310, could you update Doom and try again?

**Comment by wuqui** [comment]
> @wuqui `doom/info` issues are now resolved in [abec863](https://github.com/hlissner/doom-emacs/commit/abec86310b28da571e606d9f6489fd4b5f3a66ea), could you update Doom and try again?

Sure. Great, it works now:

```
  generated  Mar 12, 2021 12:38:18
     distro  MacOS 11.2.1 Darwin 20.3.0 x86_64
      emacs  27.1 HEAD 2003451b6 ~/.emacs.d/
       doom  2.0.9 HEAD -> develop d667a2a29 2021-03-11 17:55:29 -0500 ~/.doom.d/ -> ~/.doom.d/
      shell  /bin/zsh
   features  NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
     traits  gui server-running envvar-file
    modules  :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp ess (latex +latexmk +fold) markdown (org +roam +pretty +noter +jupyter) (python +conda) sh :config literate (default +bindings +smartparens)
   packages  (treemacs-icons-dired) (org-ref) (ox-word :recipe (:host github :repo jkitchin/scimax :files (ox-word.el))) (org-transclusion :recipe (:host github :repo nobiot/org-transclusion :branch main :files (org-transclusion.el))) (dired-narrow) (org-roam-bibtex :recipe (:host github :repo org-roam/org-roam-bibtex)) (outline-magic :recipe (:host github :repo tj64/outline-magic))
        nil  
       elpa  n/a
```

**Comment by wuqui** [comment]
Hey, I'm still facing this problem. It's really bad, I can't use Emacs for LaTeX anymore at all. Is there anything else I can do to solve or at least diagnose the problem? Anybody else who's facing the same problem?

I've just tried again, but I can't get rid of this bug. I've run `doom upgrade`, moved my config (`config.org` and `config.el`) and `packages.el` out of the way, ran `doom sync`, started Doom with vanilla config, but I still can't use `SPC` at all to insert whitespace in LaTeX mode.

**Comment by hlissner** [comment]
Sorry for the late response, but I have yet to reproduce or understand this issue. Are you still experiencing this issue?

**Comment by wuqui** [comment]
Yes, I'm still facing the same problem. 

I'm happy to take more steps that would allow you to reproduce/understand the issue. What can I do?

One more thing I had not mentioned above: this seems to be clearly tied to LaTeX mode. Everything works fine in LaTeX source blocks in org-mode, but as soon as I use `org-edit-special` to go into proper LaTeX mode, `SPC` stops working properly in insert mode, as described above.

**Comment by wuqui** [comment]
To prevent the automatic `stale` label, I can only reiterate what I said above:

> Yes, I'm still facing the same problem.
>
> I'm happy to take more steps that would allow you to reproduce/understand the issue. What can I do?
