### ISSUE TITLE
Tabs does not work with daemon

### ISSUE THREAD

**Issue by hvsouza** [doomemacs/doomemacs#6647]
### What did you expect to happen?

Centaur tabs will not work when using emacs as client. Here is the Vanilla version only enabling "tabs". It works normally when loading emacs without daemon.

![image](https://user-images.githubusercontent.com/62480697/183426376-a1d3fc34-b6c2-4097-9844-f4f495d8b5aa.png)

### What actually happened?

When opening emacs with "emacsclient -c" the tabs are not displayed

![image](https://user-images.githubusercontent.com/62480697/183426012-a09a3dd0-921f-4f54-9e44-dcd3b571f8cd.png)

### Steps to reproduce

1. Open emacs normally
2. Enable "tabs" in the init.el
3. Execute "doom sync"
4. Start daemon with "emacs --daemon" 
5. Open the client "emacsclient -c" 
6. Open any two files in the same folder.

### System Information

https://pastebin.com/KekgNm5X

**Comment by abougouffa** [comment]
I confirm this, I think it never worked on my machine (with Emacs daemon).

**Comment by shisui98** [comment]
I had this problem too. In `~/.emacs.d/modules/ui/tabs/config.el` there's a line `centaur-tabs-set-bar 'left`, I just changed it to `centaur-tabs-set-bar 'right` and that seems to have fixed the issue.
Why did I change that line? Because of this comment here: [https://github.com/ema2159/centaur-tabs/issues/127#issuecomment-894603644](url)

**Comment by abougouffa** [comment]
Thank you @shisui98.

I confirm, setting `centaur-tabs-set-bar` to `'right` fixes the problem!

**Comment by hvsouza** [comment]
That worked for me too. 
Thanks for @shisui98 and @abougouffa  !

**Comment by rongmu** [comment]
Setting `centaur-tabs-set-bar` to `'right` didn't work for me.
But this one does: https://github.com/ema2159/centaur-tabs/issues/127#issuecomment-1126913492. It turns `centaur-tabs-mode`  off and on when a new frame is created.

**Comment by ronisbr** [comment]
The solution proposed by @abougouffa fix the problem here when using GUI, and the solution mentioned by @rongmu fix the problem here when using TUI :D

**Comment by miguno** [comment]
None of the workarounds listed here worked for me.

macOS 13.5.2, Emacs 29.1 running in wezterm as terminal

**Comment by abgruszecki** [comment]
None of the workarounds work for me either, `centaur-tabs` work only if I start Emacs with `emacs`.

I'm on Ubuntu 22.04, Emacs 29.1, GUI.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/fddc912f81ce546fc3d105c99a6748b1e00ce23a, this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jrgant** [comment]
After upgrading doom so that the fix in fddc912 I am still having this problem with emacsclient (but not emacs). The only centaur-related configuration I have in `config.el` is as follows:

``` emacs-lisp
(use-package! centaur-tabs
  :hook
  ;; turn centaur-tabs-mode off for select modes
  (mu4e-view-mode . (lambda() (centaur-tabs-mode -1)))
  (inferior-ess-r-mode . (lambda() (centaur-tabs-mode -1)))
  (inferior-python-mode . (lambda() (centaur-tabs-mode -1)))
  (+doom-dashboard-mode . (lambda() (centaur-tabs-mode -1)))
  (elfeed-search-mode . (lambda() (centaur-tabs-mode -1)))
  :config
  (custom-set-faces!
   '(centaur-tabs-default :family "Inter" :height 125)
   '(centaur-tabs-selected :inherit centaur-tabs-default)
   '(centaur-tabs-selected-modified :inherit centaur-tabs-selected)
   '(centaur-tabs-unselected :inherit centaur-tabs-default)
   '(centaur-tabs-unselected-modified :inherit centaur-tabs-unselected)
   '(centaur-tabs-active-bar-face :inherit centaur-tabs-default)))
```

Things I've tried post-update (though, looking at the fix, I think these shouldn't be necessary):

- restarting the emacs daemon
- toggling centaur-tabs-mode on and off
- setting `centaur-tabs-set-bar` to `'right` 

Kubuntu 22.04.4, emacs 29.3 

Happy to provide additional info if helpful. Thanks!
