### ISSUE TITLE
Using org-roam-node-find (org-capture) will conflict with file-templates

### ISSUE THREAD

**Issue by kilesduli** [doomemacs/doomemacs#6741]
### What did you expect to happen?

Just like using org-roam normally, without the extra prefixes and warnings.

### What actually happened?

![image](https://user-images.githubusercontent.com/43215593/188055381-20dc2412-14d2-4ce9-8e93-2f37d6981814.png)

### Describe your attempts to resolve the issue

The issue is resolved by adding (set-file-template! 'org-mode :ignore t) to the config.

### Steps to reproduce

1.Use org-roam-find-note and input node name
2.the process is interrupted with a warning "Zombie snippet %?", and the newly created note buffer contains the #+TITLE:%<%Y-%m-%d> template head inserted as the title field of the org file template, resulting in: #+TITLE: #+TITLE:%<%Y-%m-%d>.

### System Information

https://pastebin.com/N3rfbm50

**Comment by kilesduli** [comment]
Have a same problem as #4271

**Comment by kilesduli** [comment]
it could be solved by `(set-file-template! "/roam/.+\\.org$" 'org-mode :ignore t)`. Although it just matches the directory where org-roam is located.

**Comment by CaptainJawZ** [comment]
> it could be solved by `(set-file-template! "/roam/.+\\.org$" 'org-mode :ignore t)`. Although it just matches the directory where org-roam is located.

This bug has been driving me crazy, even if only works for roam directory, this works perfectly for my use-case!

**Comment by ashkan-leo** [comment]
I am having the same issue. It is really annoying. The hack does not work for me. Maybe I need to modify the pattern?

**Comment by CaptainJawZ** [comment]
> I am having the same issue, and is really annoying. I was able to use the hack to solve my issue; I only had to change the regex pattern. Thanks much! A fix for this issue would be nice!

yeah I modified the "/roam/.+\\.org$" to make it match my org files directory
In my case "/home/jawz/Documents/notes/.+\\.org$"

**Comment by hlissner** [comment]
As of 802f015 I've altogether disabled file-template expansion during org-{roam-}capture, which should resolve this. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by lycheese** [comment]
I have this problem only with one specific roam template where I prompt for a folder to place the note in:
```
("h" "hierarchical" plain "%?"
           :target (file+head "%(read-directory-name \"topic: \" org-roam-directory)/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+title: ${title}\n")
           :unnarrowed t)
```

It also only happens if I don't type in the completion minibuffer and just select a directory from the list via motions. If I do type to narrow the list and then select it doesn't happen.

**Comment by simicvm** [comment]
I am still getting the `Killing zombie snippet` warning on `org-roam-capture`. 

Fresh install without any customization:
* GNU Emacs v28.2 (installed via emacs-plus)
* Doom core v3.0.0-pre 
* Doom modules v23.03.0-pre

My `init.el` org is `(org +dragndrop +pandoc +roam2)`

I don't have any other custom org-roam customization and templates.

Using provided hack does solve the issue.

**Comment by zeorin** [comment]
@simicvm I had the same error (and the double `#+title:`) until I fixed my spellcheck setup. :shrug: Turns out I hadn't actually installed all those deps correctly. Once I fixed that, this bug went away.

**Comment by simicvm** [comment]
> @simicvm I had the same error (and the double `#+title:`) until I fixed my spellcheck setup. 🤷 Turns out I hadn't actually installed all those deps correctly. Once I fixed that, this bug went away.

@zeorin hm, that could be issue. The spellchecker is acting weird, underlining correct words as incorrect. However, `doom doctor` doesn't give me anything except this:
```    
> :completion vertico
      ! The installed grep binary was not built with support for PCRE lookaheads
```

**Comment by zeorin** [comment]
`doom doctor` had also given me a clean bill of health

**Comment by Just-Insane** [comment]
This was driving me crazy all day! I thought it was caused by an unrelated package (`vulpea-create`), but no, it was apparently just having flyspell not setup correctly.

Thanks so much for this!

**Comment by bitozoid** [comment]
It also happens to me:
- not using flycheck (so nothing to setup I guess),
- doom already updated (includes https://github.com/doomemacs/doomemacs/commit/802f015f268380d40e364ca02642f5ada531b0eb),
- doom doctor says 'Everything seems fine'.

Maybe I need also to "disable file-template expansion during org-{roam-}capture". Any hint about how to do it?

Or maybe it is caused by some package that I have added to my setup.
