### ISSUE TITLE
Typescript lsp not starting with the deno lsp path not found error

### ISSUE THREAD

**Issue by aadi58002** [doomemacs/doomemacs#6744]
### What did you expect to happen?

Getting completion with typescript lsp in a next (react) project.

### What actually happened?

Do not get any sort of reasonable completion for anything like function and variable . Also am prompted to install a lsp again ( if you do not have any installed) or it will start the eslint lsp and not start the ts-ls lsp.

The lsp-log buffer had this
"deno lsp" command not found in the path

![Screenshot_20220902_120943](https://user-images.githubusercontent.com/96418027/188074460-bc5053d3-d1b1-4115-bc0f-855a30db3f35.png)

### Describe your attempts to resolve the issue

By unpinning lsp mode it resolved the issue completely but i am not sure which commit exactly on the lsp-mode fixed this issue.

### Steps to reproduce

1. Open emacs
2. Create a react or next project with typescript flag
3. Open a .tsx file
4. The lsp prompts you to install ts-ls again ( despite it being already downloaded)
5. Installing the lsp in under a second despite it being a 65 MB package

### System Information

https://pastebin.com/NZrdDRDv

**Comment by elken** [comment]
Fixed in https://github.com/doomemacs/doomemacs/pull/6721, either update your lsp pin or just unpin it

**Comment by paolo** [comment]
Hi @aadi58002 and @elken I'm still having this problem, I've tried both suggested solutions, unpin lsp-mode and also pinning it to the mentioned version on #6721, 
I do have `tsserver` available on my PATH, and I've double checked my `~/.config/emacs/.local/env` to be sure. is there anything else I could try?

**Comment by paolo** [comment]
So, I have LSP working again, it would seem to me that LSP no longer looks for the packages it needs to be available, but rather, looks for them under `.local/etc/lsp/npm` and tries to install them if not available, unpinning lsp-mode did help here, so, I just let it finish and now is working as expected.

**Comment by elken** [comment]
> So, I have LSP working again, it would seem to me that LSP no longer looks for the packages it needs to be available, but rather, looks for them under `.local/etc/lsp/npm` and tries to install them if not available, unpinning lsp-mode did help here, so, I just let it finish and now is working as expected.

Please don't comment on a closed issue. In future submit your own as closed issues are largely ignored.
