### ISSUE TITLE
`Unexpected error in Doom’s core: "lisp/lib/debug", (file-error "Cannot open load file" "Is a directory" "/lib/debug")`

### ISSUE THREAD

**Issue by nonchasd** [doomemacs/doomemacs#6766]
### What did you expect to happen?

I expect to install doom emacs

### What actually happened?

i ran doom install but got:

Eager macro-expansion failure: (void-function macroexp-file-name)
Unexpected error in Doom’s core: "lisp/lib/debug", (file-error "Cannot open load file" "Is a directory" "/lib/debug")

### Describe your attempts to resolve the issue

idk lisp so i'm useless

### Steps to reproduce

install clean emacs (i use ubuntu 22.04)
clone doom emacs into .emacs.d (like i did from the installation guide)
run .emacs.d/bin/doom install

### System Information

doom info throws the same error

**Comment by hlissner** [comment]
Already fixed in https://github.com/doomemacs/doomemacs/commit/7e0c2ed8a333522249b04b0a5815dcaac9047d6e.

**Comment by nonchasd** [comment]
@hlissner unfortunately this commit didn't solve this issue
i removed emacs completely, installed it again, cloned doom again
tried to run doom install, but got:

Eager macro-expansion failure: (void-function macroexp-file-name)
Unexpected error in Doom’s core: "lisp/lib/debug", (file-error "Cannot open load file" "Is a directory" "/lib/debug")

**Comment by hlissner** [comment]
Odd, `macroexp-file-name` is a built-in function. Are you on Emacs 27 by chance?

**Comment by hlissner** [comment]
With eb80d46 this should be fully fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by nonchasd** [comment]
emacs --version
GNU Emacs 27.1

once again i deleted emacs completely, installed it again (from apt) cloned doom
tried to run 

.emacs.d/bin/doom install
Unexpected error in Doom’s core: "lisp/lib/debug", (file-error "Cannot open load file" "Is a directory" "/lib/debug")

**Comment by hlissner** [comment]
Sigh. Looks like another 27 issue, as I can repro it there, but not in 28.1 or later.

While I figure this out, I highly recommend switching to 28.1, as 27 support will likely be removed around the end of the year. The quickest way to acquire it:

```sh
$ add-apt-repository ppa:kelleyk/emacs
$ apt update
$ apt install emacs28
```

**Comment by nonchasd** [comment]
installed emacs 28 like you suggested

cloned doom
now everything is working and doom is installed

thank you for helping me ;)

**Comment by arun-mani-j** [comment]
I have the same issue. I have Doom installed and during update, I got this error and after that even simply calling `doom` shows this error.
```sh
~ ❯ doom                      
Cannot open load file: No such file or directory, /lib/debug
```

I'm on Emacs 27.1 (Debian Testing). Is it easy to fix it or shall I just reinstall?

Thanks for Doom Emacs <3

**Comment by hlissner** [comment]
As of 3505e66 this should be fixed for 27.x users. 

That said, you may need to update manually to get around the error:

```sh
cd ~/.emacs.d
git pull
doom sync -u
```

**Comment by arun-mani-j** [comment]
Thanks! It worked.
