### ISSUE TITLE
`Error: Failed to load Doom from <non-standard location>/early-init.el`

### ISSUE THREAD

**Issue by quzyte** [doomemacs/doomemacs#6777]
### What did you expect to happen?

I tried to clone and install Doom in a different directory (according to the [documentation](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#install-doom-alongside-other-configs-with-chemacs2)). Ideally, there should be no errors.

### What actually happened?

But instead, `doom install` fails, with output:
>Error: Failed to load Doom from [...]/early-init.el

This was due to early-init.el not recognising automatically that it was in a non-default directory (When I tried to install again in the default directory, the error vanished).

### Describe your attempts to resolve the issue

- **Attempt 1**
So, I tried to explicitly pass the directory via the option `--emacsdir` but this did not work either.
Reading through the `bin/doom` file, I found that `early-init.el` is being called before these options are processed by `bin/doom`. 

- **Attempt 2**
So, finally, I exported `$EMACSDIR` to `env` and then ran the command.
This time, it ran successfully.

I am not sure if this is normal behaviour, or if `doom` and `early-init.el` are supposed to infer `EMACSDIR` automatically (based on the location of the cloned doom repo.

In any case, the documentation does not correspond to the behaviour, and one of those should be modified.

### Steps to reproduce

- Clone Doom Emacs to non-default directory:
`git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs-doom.d`
- Install Doom with
`~/doom-emacs/bin/doom install`
or even pass directory with option --emacsdir.
This raises error:
    >Error: Failed to load Doom from [...]/early-init.el

### System Information

`doom info` fails with same error

**Comment by podung** [comment]
@quzyte workaround posted in #6781 - just do a `git checkout 3853dff5e` and try again.  Looks like a commit from a couple weeks ago introduced this issue

**Comment by hlissner** [comment]
I just pushed a laundry list of changes in https://github.com/doomemacs/doomemacs/compare/29e30e8af4b9...b395bd5392dd. Please see if updating Doom fixes this issue.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jasonjckn** [comment]
@hlissner I'm still getting an error with non-standard locations

Steps I took
```
git clone https://github.com/doomemacs/doomemacs ~/.emacs/plus-30
~/.emacs/plus-30/bin/doom install
```

Using git hash # 811c18ca680d31b411ce395e0d28ab97816f177a
Emacs version 28.2 - from https://bitbucket.org/mituharu/emacs-mac (also produces with v29)

Here's the stdout i get
```
❯ ~/.emacs/plus-30/bin/doom install

Error: wrong-type-argument (stringp nil)
  debug-early-backtrace()
  debug-early(error (wrong-type-argument stringp nil))
  load(nil noerror nomessage nil must-suffix)
  (or (let (file-name-handler-alist) (if user-emacs-directory nil (setq user-emacs-directory (file-name-directory (file-truename load-file-name)))) (let ((initdir (or (car (cdr (member "--init-directory" command-line-args))) (getenv-internal "EMACSDIR")))) (if initdir (progn (setq command-switch-alist (cons (cons "--init-directory" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setq user-emacs-directory (expand-file-name initdir))))) (let ((profile (or (car (cdr (member "--profile" command-line-args))) (getenv-internal "DOOMPROFILE")))) (if profile (progn (setq command-switch-alist (cons (cons "--profile" #'(lambda (_) (car-safe (prog1 argv (setq argv (cdr argv)))))) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (expand-file-name (format "profiles/init.%d" emacs-major-version) user-emacs-directory) 'noerror 'nomessage nil t) (user-error "Profiles not initialized yet; run 'doom sync' first"))))) (if (let ((load-suffixes '(".elc" ".el"))) (load (expand-file-name "lisp/doom" user-emacs-directory) 'noerror 'nomessage nil 'must-suffix)) (doom-require (if noninteractive 'doom-cli 'doom-start)) (progn (setq user-init-file (expand-file-name "early-init" user-emacs-directory)) (setq load-prefer-newer t)) nil)) (load early-init-file 'noerror 'nomessage nil 'must-suffix))
  load-with-code-conversion("/Users/jbjack1/.emacs/plus-30/early-init.el" "/Users/jbjack1/.emacs/plus-30/early-init.el" nil t)
  load("/Users/jbjack1/.emacs/plus-30/early-init.el" nil nomessage)
  (and (load init-file nil 'nomessage) (featurep 'doom))
  (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/Users/jbjack1/.emacs/plus-30/bin/doom" "/Users/jbjack1/.emacs/plus-30/bin/doom" nil t)
  command-line-1(("--load" "/Users/jbjack1/.emacs/plus-30/bin/doom" "--" "install"))
  command-line()
  normal-top-level()
Wrong type argument: stringp, nil

```

**Comment by marienz** [comment]
Using revision 811c18ca680d31b411ce395e0d28ab97816f177a installed in ~/src/doom-emacs, chemacs2 in ~/.emacs.d, and Emacs 28.1.50 (a Git snapshot from [Fedora Copr](https://copr.fedorainfracloud.org/coprs/faultline/emacs-pgtk-nativecomp/)) I'm getting what looks like the same problem as @jasonjckn:

```
$ doom sync
startup args: (emacs --load /home/marienz/src/doom-emacs/bin/doom -- sync)
EMACSDIR: nil
startup user-emacs-directory: ~/.emacs.d/
loading from user-emacs-directory: ~/.emacs.d/
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  load(nil noerror nomessage nil must-suffix)
  (or (let (file-name-handler-alist) (message "startup user-emacs-directory: %s" user-emacs-directory) (if user-emacs-directory nil (message "setting user-emacs-directory") (setq user-emacs-directory (file-name-directory (file-truename load-file-name)))) (let ((initdir (or (car (cdr ...)) (getenv-internal "EMACSDIR")))) (if initdir (progn (setq command-switch-alist (cons (cons "--init-directory" ...) command-switch-alist)) (setq user-emacs-directory (expand-file-name initdir))))) (let ((profile (or (car (cdr ...)) (getenv-internal "DOOMPROFILE")))) (if profile (progn (setq command-switch-alist (cons (cons "--profile" ...) command-switch-alist)) (setenv "DOOMPROFILE" profile) (or (load (expand-file-name ... user-emacs-directory) 'noerror 'nomessage nil t) (user-error "Profiles not initialized yet; run 'doom sync' firs..."))))) (if (let ((load-suffixes '(".elc" ".el"))) (message "%s" user-emacs-directory) (load (expand-file-name "lisp/doom" user-emacs-directory) 'noerror 'nomessage nil 'must-suffix)) (doom-require (if noninteractive 'doom-cli 'doom-start)) (setq user-init-file (expand-file-name "early-init" user-emacs-directory) load-prefer-newer t) nil)) (load early-init-file 'noerror 'nomessage nil 'must-suffix))
  load-with-code-conversion("/home/marienz/src/doom-emacs/early-init.el" "/home/marienz/src/doom-emacs/early-init.el" nil t)
  load("/home/marienz/src/doom-emacs/early-init.el" nil nomessage)
  (and (load init-file nil 'nomessage) (featurep 'doom))
  (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))
  (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file)))
  (condition-case e (let* ((bin-dir (file-name-directory (file-truename load-file-name))) (init-file (expand-file-name "../early-init.el" bin-dir))) (or (and (load init-file nil 'nomessage) (featurep 'doom)) (user-error "Failed to load Doom from %s" init-file))) (user-error (message "Error: %s" (car (cdr e))) (kill-emacs 2)))
  load-with-code-conversion("/home/marienz/src/doom-emacs/bin/doom" "/home/marienz/src/doom-emacs/bin/doom" nil t)
  command-line-1(("--load" "/home/marienz/src/doom-emacs/bin/doom" "--" "sync"))
  command-line()
  normal-top-level()
```
Those prints before the backtrace are from:
```.patch
diff --git a/early-init.el b/early-init.el
index d4b47d829..7cc76d596 100644
--- a/early-init.el
+++ b/early-init.el
@@ -47,6 +47,9 @@
    ;; FIX: If this file was loaded via -batch or bin/doom, then
    ;;   `user-emacs-directory' won't be set. As a starting point, let's assume
    ;;   it's the directory this early-init.el file lives in.
+   (message "startup args: %s" command-line-args)
+   (message "EMACSDIR: %s" (getenv-internal "EMACSDIR"))
+   (message "startup user-emacs-directory: %s" user-emacs-directory)
    (unless user-emacs-directory
      (setq user-emacs-directory (file-name-directory (file-truename load-file-name))))

@@ -90,6 +93,7 @@
    ;;   `load'. See the docs of `load' for details.
    (if (let ((load-suffixes '(".elc" ".el")))
          ;; Load the heart of Doom Emacs.
+        (message "loading from user-emacs-directory: %s" user-emacs-directory)
          (load (expand-file-name "lisp/doom" user-emacs-directory)
                'noerror 'nomessage nil 'must-suffix))
        ;; ...and prepare for the rest of the session.
```

If I run `emacs`, chemacs sets `user-emacs-directory` to ~/src/doom-emacs as intended and we get further (to an error asking me to run `doom sync`). If I run `doom`, a comment in early-init.el says it expects `user-emacs-directory` will be unset and needs to be set to the directory early-init.el is in, but it's actually set to the directory chemacs2 is in (and that's not overridden before Doom tries to load itself from there). It looks like `doom` runs `emacs` with `-q` (it's just deleted from `command-line-args` before I print it), so we skipped chemacs. I haven't tracked down what in Emacs itself ends up setting `user-emacs-directory` instead (but there's some code for it in startup.el early in `normal-top-level` that looks like it'd do it).

If I drop the `unless` and unconditionally `(setq user-emacs-directory (file-name-directory (file-truename load-file-name)))` early in early-init.-el, that seems to work in my setup (but I haven't thought about what other setups it might break instead...).

**Comment by hlissner** [comment]
As of f748a5d this issue should finally be put to rest. Let me know if that isn't the case!

**Comment by honghuzi** [comment]
Everything works fine on the newest version! I'll also try replaceing Chemacs with doom emacs's profile managing strategy.

**Comment by ryukinix** [comment]
I am still experiencing this issue.

**Comment by costis-t** [comment]
For me this error happened because I had set the ``EMACSDIR`` (most likely) or/and ``EMACS_USER_DIR`` path under .config from a previous installation. ``unset``  related variables and installation started.
