### ISSUE TITLE
`doom doctor` (geiser-activate-implementation) function definition is void with `(scheme +guile)`

### ISSUE THREAD

**Issue by offsetcyan** [doomemacs/doomemacs#7472]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When `doom doctor` is run, I expect to see an output of packages and configuration suggested to complete Doom's feature set as an IDE, if the configuration in init.el is correct.

### Current behavior

`doom doctor` raises an unexpected error with respect to geiser if `(scheme +guile)` is part of the synced init.el (`.emacs.d/.local/etc/@/init.29.el`). The error is not raised if just `(scheme)` is set.

In  .local/etc/@/init.29.el, the function definition  (defun geiser-activate-implementation ...) is on line 17831, but the call to it with (geiser-activate-implementation 'guile) was on line 17619, so no wonder it wasn't defined.

```
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-activate-implementation)
    Backtrace:
      (geiser-activate-implementation 'guile)
      (load-with-code-conversion "/home/user/.emacs.d/.local/etc/@/init.29.el" "/home/user/.emacs.d/.local/etc/@/init.29.el" t t)
      (load "/home/user/.emacs.d/.local/etc/@/init.29.el" noerror nomessage)
      ... ;; full log attached
```
[cli.doom.230929033925.2850084.error.txt](https://github.com/doomemacs/doomemacs/files/12755604/cli.doom.230929033925.2850084.error.txt)

### Steps to reproduce

1. In Doom's init.el, enable `(scheme +guile)`.
2. `doom sync`.
3. `doom doctor` will error.

### System Information

https://pastebin.com/KufKL6HA

**Comment by rootex-** [comment]
Confirm, I have the same behavior

**Comment by easbarba** [comment]
Same here, had to disable +guile for a while(2months)

**Comment by kGAr6Naaes** [comment]
Same here, for now I'm gonna comment out Scheme.

I tried 

```shell
doom sync
doom purge
``` 

as @easbarba suggested and it didn't work.

**Comment by OrionRandD** [comment]
> Confirm, I have the same behavior

me too...

GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0) of 2023-08-30, modified by Debian

in my init I have:
;; (scheme +chez +guile +mit +racket +stklos) ; a fully conniving family of lisps
(scheme +guile +mit +racket +stklos) ; a fully conniving family of lisps

and this is the error:

> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-activate-implementation)
    Backtrace:
      (geiser-activate-implementation 'guile)

I have tried a few fixes, but to no avail...
But, came to this tread and now I know it seems to be a bug or sort of...
:(

**Comment by hlissner** [comment]
As of 87f6f7a this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pfmaggi** [comment]
I've now this error (I didn't experience it in the past).

### Version
```
$ doom version                                                                                                       
GNU Emacs     v29.1            nil
Doom core     v3.0.0-pre       HEAD -> master 87f6f7ab 2023-11-29 13:41:23 -0500
Doom modules  v23.09.0-pre     HEAD -> master 87f6f7ab 2023-11-29 13:41:23 -0500``
```

in `init.el`I have:
```
(scheme +guile)      ; a fully conniving family of lisps
```
running `doom doctor`:
```
$ doom doctor                                                                                                                                  
The doctor will see you now...                                                                                                                                                                     
                                                                                                                                                                                                   
> Checking your Emacs version...                                                                                                                                                                   
> Checking for Doom's prerequisites...                                                                                                                                                             
> Checking for Emacs config conflicts...                                                                                                                                                           
> Checking for missing Emacs features...                                                                                                                                                           
  ! Emacs was not built with native compilation support                                                                                                                                            
    Users will see a substantial performance gain by building Emacs with                                                                                                                           
    native compilation support, availible in emacs 28+.You must install a
    prebuilt Emacs binary with this included, or compile Emacs with the
    --with-native-compilation option.
> Checking for private config conflicts...
> Checking for common environmental issues...
! Detected Fish as your $SHELL
  Fish (and possibly other non-POSIX shells) is known to inject garbage
  output into some of the child processes that Emacs spawns. Many Emacs
  packages/utilities will choke on this output, causing unpredictable
  issues. To get around this, either:
   
    - Add the following to $DOOMDIR/config.el:
   
      (setq shell-file-name (executable-find "bash"))
   
    - Or change your default shell to a POSIX shell (like bash or zsh)
      and explicitly configure your terminal apps to use the shell you
      want.
   
  If you opt for option 1 and use one of Emacs' terminal emulators, you
  will also need to configure them to use Fish, e.g.
   
    (setq-default vterm-shell (executable-find "fish"))
   
    (setq-default explicit-shell-file-name (executable-find "fish"))
   
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-activate-implementation)
    Backtrace:
      (geiser-activate-implementation 'guile)
      (eval-buffer #<buffer  *load*-860382> nil "/home/pmaggi/.config/emacs/.local/etc/@/init.29.el" nil t)
      (load-with-code-conversion "/home/pmaggi/.config/emacs/.local/etc/@/init.29.el" "/home/pmaggi/.config/emacs/.local/etc/@/init.29.el" t t)
      (load "/home/pmaggi/.config/emacs/.local/etc/@/init.29.el" noerror nomessage)
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ...
      (doom-load "/home/pmaggi/.config/emacs/.local/etc/@/init.29.el" noerror)
      (let (kill-emacs-query-functions kill-emacs-hook) (doom-load init-file 'noerror) (doom-initialize-packages))
      (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did you forgot to run 'doom sync'?")) (let (kill-emac...
      (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did you forgot t...
      (if noninteractive (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generate...
      (eval-buffer #<buffer  *load*-657611> nil "/home/pmaggi/.config/emacs/lisp/doom-start.el" nil t)
      (load-with-code-conversion "/home/pmaggi/.config/emacs/lisp/doom-start.el" "/home/pmaggi/.config/emacs/lisp/doom-start.el" nil t)
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.231129211241.17121.error
 
````

I use the fish shell but even setting ` (setq shell-file-name (executable-find "bash"))` doesn't seem to solve this issue.

**Comment by hlissner** [comment]
Ah, I can reproduce this. Appears to be a build order issue. `geiser-guile` calls `(geiser-activate-implementation 'guile)` in its autoloads file, before the `geiser` package has a chance to define the `geiser-activate-implementation` function. Looking into a solution.

**Comment by hlissner** [comment]
Should be fixed in f9c2397. Let me know if that isn't the case!

**Comment by hugonobrega** [comment]
> Should be fixed in [f9c2397](https://github.com/doomemacs/doomemacs/commit/f9c2397a3cee34732b8279bba49af1e6f09eb113). Let me know if that isn't the case!

I am still seeing this issue on a fully up-to-date doom (rebuilt all packages too)

**Comment by hugonobrega** [comment]
I'm slightly puzzled as to what may have happened, but after having the `:lang (scheme +guile)` turned off for a few days because of this issue, I just re-enabled it and didn't get the issue this time.

**Comment by Ecsodikas** [comment]
I also get the same error after enabling `(scheme +chicken)` in the init.el file.

```
➜  ~ doom doctor     
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-activate-implementation)
    Backtrace:
      (geiser-activate-implementation 'chicken)
      (load-with-code-conversion "/home/ecsodikas/.config/emacs/.local/etc/@/init.29.el" "/home/ecsodikas/.config/emacs/.local/etc/@/init.29.el" t t)
      (load "/home/ecsodikas/.config/emacs/.local/etc/@/init.29.el" noerror nomessage)
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (signal (cond ((not (a...
      (doom-load "/home/ecsodikas/.config/emacs/.local/etc/@/init.29.el" noerror)
      (let (kill-emacs-query-functions kill-emacs-hook) (doom-load init-file 'noerror) (doom-initialize-packages))
      (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did you forgot to run 'doom sync'?")) (let (kill-emacs-query-...
      (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did you forgot to run 'd...
      (if noninteractive (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did y...
      (load-with-code-conversion "/home/ecsodikas/.config/emacs/lisp/doom-start.el" "/home/ecsodikas/.config/emacs/lisp/doom-start.el" nil t)
      (require doom-start)
      (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-indent-increment) 0) doom-print-indent))) (require 'doom-start) (doom-print (doom-print--format...
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.231214004235.50442.error

```
I was running Emacs 27 before and was wondering if this was the issue, but I upgraded to 29 and did a fresh `doom sync` and sadly the error persists. Maybe this helps debugging the issue.

**Comment by jidibinlin** [comment]
I got this errors too

**Comment by reyman** [comment]
Same problem here !

**Comment by rubin55** [comment]
I've been getting this error for the last two months. Just now I rm -rf ~/.emacs.d/.local, I git pull and am on `03d692f129633e3bf0bd100d91b3ebf3f77db6d1`. I then `doom upgrade` and let it finish. I immediately get the error after starting emacs.

**Comment by flatwhatson** [comment]
I'm also seeing this issue on the latest master 03d692f129633e3bf0bd100d91b3ebf3f77db6d1.  Using the following workaround:
```elisp
;;; .local/etc/@/init.29.d/85-loaddefs.hacks.el
(require 'geiser-autoloads)
(require 'geiser-guile-autoloads)
```

**Comment by OrionRandD** [comment]
> I'm also seeing this issue on the latest master [03d692f](https://github.com/doomemacs/doomemacs/commit/03d692f129633e3bf0bd100d91b3ebf3f77db6d1). Using the following workaround:
> 
> ```emacs-lisp
> ;;; .local/etc/@/init.29.d/85-loaddefs.hacks.el
> (require 'geiser-autoloads)
> (require 'geiser-guile-autoloads)
> ```
> 
> Make sure you've put it in the correct `init.XY.d` for your emacs version, and run `doom sync` afterwards to recompile the init files before running emacs.

The hack seems to have worked here...
Thx.

**Comment by sausageandbiscuits** [comment]
Got the same error. Tried removing `+racket` running `doom sync`, re-adding `+racket` , doing `doom sync` again and then it worked for me.

**Comment by mmohammadi9812** [comment]
I'm having the same error too, can't use guile scheme, I'm using emacs 29.1 and [latest doom commit](https://github.com/ray1729/doomemacs/commit/517daa4ed9168855c202ba2fd28920f6ee17249f), any updates on this error?

**Comment by ninioArtillero** [comment]
> I'm having the same error too, can't use guile scheme, I'm using emacs 29.1 and [latest doom commit](https://github.com/ray1729/doomemacs/commit/517daa4ed9168855c202ba2fd28920f6ee17249f), any updates on this error?
 
 Are you having the following message in the error log?
 
```
 $ cd /home/USER/.emacs.d/.local/straight/repos/flycheck-guile/
$ git rev-parse HEAD
HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[Return code: 128]
```

Guess we should open a new issue, but I'll look into it as soon as possible.

**Comment by vvzen** [comment]
Same here on my fresh install (literally cloned today) :
```bash
$ emacs --version
GNU Emacs 29.4
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ doom --version
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD c8a5e6e 2024-09-17 17:30:57 -0400
Doom modules  v24.10.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD c8a5e6e 2024-09-17 17:30:57 -0400

Copyright (c) 2014-2024 Henrik Lissner.

Doom Emacs uses the MIT license and is provided without warranty of
any kind. You may redistribute and modify copies if given proper
attribution. See the LICENSE file for details.

$ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-activate-implementation)
    Backtrace:
      (geiser-activate-implementation 'chicken)
      (eval-buffer #<buffer  *load*-586314> nil "/home/vv/.config/emacs/.local/etc/@/init.29.el" nil t)
      (load-with-code-conversion "/home/vv/.config/emacs/.local/etc/@/init.29.el" "/home/vv/.config/emacs/.local/etc/@/init.29.el" t t)
      (load "/home/vv/.config/emacs/.local/etc/@/init.29.el" noerror nomessage)
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-s...
      (doom-load "/home/vv/.config/emacs/.local/etc/@/init.29.el" noerror)
      (let (kill-emacs-query-functions kill-emacs-hook) (doom-load init-file 'noerror) (doom-initialize-packages))
      (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been generated. Did you forgot to run 'doom ...
      (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init file hasn't been ge...
      (if noninteractive (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-file) nil (user-error "Profile init ...
      (eval-buffer #<buffer  *load*-511777> nil "/home/vv/.config/emacs/lisp/doom-start.el" nil t)
      (load-with-code-conversion "/home/vv/.config/emacs/lisp/doom-start.el" "/home/vv/.config/emacs/lisp/doom-start.el" nil t)
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD c8a5e6e 2024-09-17 17:30:57 -0400
Doom modules  v24.10.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD c8a5e6e 2024-09-17 17:30:57 -0400
```

( As a workaround, I was able to get past it after commenting the `(scheme +chicken)` entry in my `~/.config/doom/init.el` )

**Comment by justjoheinz** [comment]
Same issue here - I could get around it by 

- installing (scheme +chicken), doom sync, doom doctor, (error present)
- remove +chicken, doom sync, doom doctor
- add +chicken, doom sync, doom doctor (error gone)

After +chicken had been added again the error was gone.

**Comment by ninioArtillero** [comment]
In my case the repository was headless (don't known how that happened), so after setting up the remote tracking branch again everything `doom sync` went smooth. My usual goto fix after nothing works is to erase all of `.emacs.d/.local/straight/repos/` but I forgot it this time and would have probably worked too.
