### ISSUE TITLE
`emacsclient -c` doesn't open frames anymore on wayland

### ISSUE THREAD

**Issue by j-palms** [doomemacs/doomemacs#8059]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After running `emacs --fg-daemon`, `emacsclient -c` should open frames.

### Current behavior

Running `emacsclient -c` does not open frames. In the emacs daemon log appears the following error: `gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed`
Running emacs as standalone instance with `doom run` is working fine.

The behaviour just started recently. I tracked down the cause to this commit: https://github.com/doomemacs/doomemacs/commit/9753bfb775d04cedaa955a92b3e2256ceb28b0cc
After excluding it, everything works again.

### Steps to reproduce

1. System: Arch Linux with Wayland (Hyprland), `emacs-wayland` package (with pure-GTK)
2. Run `emacs --fg-daemon`
3. Run `emacsclient -c`

### System Information

https://pastebin.com/hmwky4Bs

**Comment by hlissner** [comment]
If you don't spot any warnings/errors, see if this fixes your issue:

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! fixed-doom--load-theme-a (theme &optional no-confirm no-enable)
  "Record `doom-theme', disable old themes, and trigger `doom-load-theme-hook'."
  :override #'doom--load-theme-a
  (with-temp-buffer
    (let ((last-themes (copy-sequence custom-enabled-themes)))
      (mapc #'disable-theme custom-enabled-themes)
      (prog1 (funcall fn theme no-confirm no-enable)
        (when (and (not no-enable) (custom-theme-enabled-p theme))
          (setq doom-theme theme)
          (put 'doom-theme 'previous-themes (or last-themes 'none))
          (doom-run-hooks 'doom-load-theme-hook))))))

(add-hook! 'before-make-frame-hook
  (setf (alist-get 'foreground-color default-frame-alist) (face-foreground 'default nil t)
        (alist-get 'background-color default-frame-alist) (face-background 'default nil t)))
```

**Comment by j-palms** [comment]
There is the one error that I already mentioned: `gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed`.

**Comment by hlissner** [comment]
I meant elisp errors/warnings, but I'll take it that means you didn't see any. I'm inclined to call this a (P)GTK issue than a Doom issue, since I can't reproduce it. I'll revisit this when I have more leads.

**Comment by hlissner** [comment]
This may be related to https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-07/msg02081.html (which was fixed in Emacs v30 here: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=74d6604eaa2d770626309181ac4bc4f2598e63e7), but versions of PGTK before 30 could be subject to crashes. Are you able to upgrade to Emacs 30+?

**Comment by hlissner** [comment]
Let me know if 86b7bef helps your issue.

**Comment by tricera-josua-palmstedt** [comment]
No unfortunately https://github.com/doomemacs/doomemacs/commit/86b7bef5127c48e94df1c4f515f517383913d368 does not fix it.
And using emacs 30.0.90 doesn't either (instead giving some new problems..).

I noticed some differences that may be worth mentioning:
- `doom run` and then calling `emacsclient -c` (from terminal or with the keybinding) opens a new frame as it should 
- `emacs --fg-daemon` and then calling `emacsclient -c` from terminal opens terminal version of emacs
- `emacs --fg-daemon` and then pressing my keybinding for doom emacs (which is also `emacsclient -c`) opens nothing and gives the error I mentioned in the posts before

**Comment by j-palms** [comment]
No unfortunately https://github.com/doomemacs/doomemacs/commit/86b7bef5127c48e94df1c4f515f517383913d368 does not fix it. Neither does moving to emacs 30.0.90 (which instead leads to some new errors..),

I noticed some differences in behaviour that maybe worth mentioning:
- ´doom run´ and then ´emacsclient -c´ (directly from terminal or as keybinding) opens a new frame as it should
- ´emacs --fg-daemon´ and then ´emacsclient -c´ from terminal opens the terminal version of emacs
- ´emacs --fg-daemon´ and pressing the keybinding (which also executes ´emacsclient -c´ does nothing and gives the error I mentioned in the posts before

**Comment by hlissner** [comment]
> emacs --fg-daemon and then emacsclient -c from terminal opens the terminal version of emacs

This suggests that `doom run` and `emacs --fg-daemon` may be launching different `emacs` executables. `emacsclient -c` not opening a GUI frame usually means Emacs isn't built with GUI support. Grab your `M-x doom/info` from that terminal frame so I can confirm that.

> emacs --fg-daemon and pressing the keybinding (which also executes emacsclient -c does nothing and gives the error I mentioned in the posts before

To double check: `emacs --fg-daemon --debug-init` + `emacsclient -nw` (or `emacsclient -c`) isn't producing a backtrace? Or any, more informative errors?

**Comment by hlissner** [comment]
Here's another snippet to try:

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! fixed-doom--load-theme-a (fn theme &optional no-confirm no-enable)
  "Record `doom-theme', disable old themes, and trigger `doom-load-theme-hook'."
  :override #'doom--load-theme-a
  (with-temp-buffer
    (let ((last-themes (copy-sequence custom-enabled-themes)))
      (mapc #'disable-theme custom-enabled-themes)
      (prog1 (funcall fn theme no-confirm no-enable)
        (when (and (not no-enable) (custom-theme-enabled-p theme))
          (setq doom-theme theme)
          (put 'doom-theme 'previous-themes (or last-themes 'none))
          (doom-run-hooks 'doom-load-theme-hook))))))

(add-to-list 'frame-inherited-parameters 'background-color)
(add-to-list 'frame-inherited-parameters 'foreground-color)
(add-to-list 'frame-inherited-parameters 'cursor-color)
(add-to-list 'frame-inherited-parameters 'border-color)
(add-to-list 'frame-inherited-parameters 'mouse-color)
```

**Comment by j-palms** [comment]
`emacsclient -c` with terminal Emacs: https://pastebin.com/pu9Pvmz3
There should be only one emacs executable on my system. I thought that probably because the Emacs GUI fails it automatically falls back to the terminal version.

And `emacs --fg-daemon --debug-init` does not give any more informative errors.

**Comment by j-palms** [comment]
I just realized that `emacs --fg-daemon` + `emacsclient -c` always results in the GTK error and then a terminal emacs. In the case of the keybinding this terminal emacs just opens in the tty1 behind the display manager.

**Comment by hlissner** [comment]
> I thought that probably because the Emacs GUI fails it automatically falls back to the terminal version.

Yes and no. If Emacs is incapable of producing a GUI frame, it will fall back to creating a terminal frame, but "incapable" means it wasn't compiled with the functionality. Elisp (or any runtime) errors don't count; they'll just prevent any frame from being created at all.

Another possibility is that Emacs can't see your $WAYLAND_DISPLAY. Try specifying it in the `emacsclient` call (with the `-d` option):

```sh
emacsclient -c -d $WAYLAND_DISPLAY
;; or
emacsclient -c -d :0     # I know this is an X-style display descriptor, but
                         # I'm running out of ideas...
```

**Comment by j-palms** [comment]
No it seems it already had access to the $WAYLAND_DISPLAY because passing `wayland-1` doesn't change the behaviour, while passing something else results in `(emacs:117073): Gtk-WARNING **: 16:11:31.060: cannot open display: : ...`

Closing the client makes the daemon crash with:
`Debugger entered--Lisp error: (wrong-type-argument frame-live-p #<dead frame F2 0x63db3e5e54e0>)
  select-frame(#<dead frame F2 0x63db3e5e54e0> norecord)
  persp-delete-frame(#<dead frame F2 0x63db3e5e54e0>)
  run-hook-with-args(persp-delete-frame #<dead frame F2 0x63db3e5e54e0>)
  apply(run-hook-with-args (delete-frame-functions #<dead frame F2 0x63db3e5e54e0>))
`
But I'm back on 29.4 now, because 30.0.90 gave me numerous other errors.

**Comment by wrightgardner** [comment]
For me, it turned out to be theme switching logic:

```elisp
(defun my/apply-theme (appearance)
  (mapc #'disable-theme custom-enabled-themes)
  (pcase appearance
    ('light
     (setq doom-theme 'doom-tokyo-night)
     (load-theme 'doom-tokyo-night t)
     )
    ('dark
     (setq doom-theme 'doom-tokyo-night)
     (load-theme 'doom-solarized-light t)
    )
  )
)

(add-hook! 'ns-system-appearance-change-functions #'my/apply-theme)
```

If I  comment out the add-hook, emacsclient loads fine again.

**Comment by 15cm** [comment]
Same issue. Resetting the commit to the rev before https://github.com/doomemacs/doomemacs/commit/9753bfb775d04cedaa955a92b3e2256ceb28b0cc fixed it. I'm also on NixOS + Hyprland + emacs-pgtk of https://github.com/nix-community/emacs-overlay/commit/d2e8a913f490f0022b9fe9c54e419e3ab134687c .

My doom config also have theme related hooks https://github.com/15cm/doomemacs-config/blob/5163162b2bf1c7204197ea7729d14ae95f4c0d3e/config.el#L25-L27 -> https://github.com/15cm/nixfiles/blob/main/home/modules/programs/emacs/scripts/load-theme.el.jinja . But commenting them out didn't help.

**Comment by hlissner** [comment]
@15cm Does it help if you comment out [these lines](https://github.com/15cm/doomemacs-config/blob/5163162b2bf1c7204197ea7729d14ae95f4c0d3e/config.el#L49-L50)?

If not, how about 240493ae9235d2b1b2ffc1d98cd829b7d2bbb236?

**Comment by j-palms** [comment]
With https://github.com/doomemacs/doomemacs/commit/240493ae9235d2b1b2ffc1d98cd829b7d2bbb236 `emacsclient -c` still doesn't open a frame. But now there is also no GTK error and also no terminal emacs anymore.

**Comment by j-palms** [comment]
Mmh maybe this is related to Hyprland?

**Comment by hlissner** [comment]
Hard to say. I'm on [Hyprland@b9b8e62](https://github.com/hyprwm/Hyprland/commit/b9b8e6220f55af34e862b541a5a4b30ae6d8f15f) myself and haven't been able to repro it.

Does unsetting `frame-inherited-parameters` fix it for you? E.g.

```lisp
;;; add to $DOOMDIR/config.el
(setq frame-inherited-parameters nil)
```

**Comment by j-palms** [comment]
Yes it does! The first call of `emacsclient -c` took quite long so that I killed it, but now it just works.

**Comment by hlissner** [comment]
Urg. I think I see the cause. Emacs tries to copy `background-color` and `foreground-color` from the invisible daemon frame (which is set to `unspecified-{fg,bg}`, which isn't a valid color) to the new frame, and the invalid color crashes the frame. Guess I'll have to find a safer way to set these parameters.

**Comment by hlissner** [comment]
Phew! 9359a81 should finally put this to rest. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by j-palms** [comment]
Awesome :) Thanks for fixing it!
