### ISSUE TITLE
`(wrong-type-argument stringp nil)` error from `doom--startup-package-autoloads` at startup

### ISSUE THREAD

**Issue by johanwiden** [doomemacs/doomemacs#8143]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

With module debugger enabled emacs would fail at startup, and complain about an undefined variable.
Not a big problem for me, as I do not use this module at present. This is mainly to help other users who may run in to this problem.

Warning (initialization): An error occurred while booting Doom Emacs:

Wrong type argument: stringp, nil

### Current behavior

When I execute emacs --debug-init i get:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  doom--startup-package-autoloads()
  doom-startup()
  (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup))
  (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))
  (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup))))
  (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda (s) (prin1-to-string s t)) (cdr error) ", ")) :warning) (setq init-file-had-error t)))
  (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda ... ...) (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error))))
  (let ((debug-on-error-from-init-file nil) (debug-on-error-should-be-set nil) (debug-on-error-initial (if (eq init-file-debug t) 'startup init-file-debug)) (inhibit-null-byte-detection t)) (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name ...)) (setq user-init-file (concat ... ".el")) (setq load-history (delete ... load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'... (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error)))) (if debug-on-error-should-be-set (progn (setq debug-on-error debug-on-error-from-init-file))))
  startup--load-user-init-file@init-doom(#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t)
  apply(startup--load-user-init-file@init-doom (#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t))
  #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom)))(#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t)
  apply(#f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) (#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t))
  #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files)))(#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t)
  apply(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) (#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t))
  (unwind-protect (apply fn args) (progn (set-default 'inhibit-message nil)) (advice-remove #'tool-bar-setup #'ignore) (let ((sym 'tool-bar-mode)) (defalias 'doom-transient-hook5 #'(lambda (&rest _) "Transient hook for tool-bar-mode" (tool-bar-setup) (let ((sym ...)) (cond (... ...) (... ...))) (unintern 'doom-transient-hook5 nil))) (cond ((functionp sym) (advice-add 'tool-bar-mode :before #'doom-transient-hook5)) ((symbolp sym) (put 'doom-transient-hook5 'permanent-local-hook t) (add-hook sym #'doom-transient-hook5 nil)))) (if (default-toplevel-value 'mode-line-format) nil (progn (set-default 'mode-line-format (get 'mode-line-format 'initial-value)))))
  startup--load-user-init-file@undo-hacks(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) #f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t)
  apply(startup--load-user-init-file@undo-hacks #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) (#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t))
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x14d2dd6391fbb496>) #f(compiled-function () #<bytecode -0x15951949e52a224f>) t)
  command-line()
  normal-top-level()
```

### Steps to reproduce

1. With module debugger enabled in init.el, execute emacs

### System Information

https://pastebin.com/FPDVxKxh

**Comment by warpje5** [comment]
same here with 29.4

[an error](https://pastebin.com/h2ETfnik)

**Comment by hlissner** [comment]
I've managed to reproduce this and a fix will be up shortly.

**Comment by hlissner** [comment]
As of 114f996 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Timothy-W-Hilton** [comment]
Many thanks, Henrik!   I'm getting a different error now.  [emacs --debug-init output](https://gist.github.com/Timothy-W-Hilton/59ffea265ab20fa61a6c37459cfe6593).
```

⛔ Warning (initialization): An error occurred while booting Doom Emacs:

Symbol's value as variable is void: json-mode-auto-mode-list

To ensure normal operation, you should investigate and remove the
cause of the error in your Doom config files. Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by hlissner** [comment]
@Timothy-W-Hilton Whoops. b26980a should fix that.

**Comment by Timothy-W-Hilton** [comment]
> [@Timothy-W-Hilton](https://github.com/Timothy-W-Hilton) Whoops. [b26980a](https://github.com/doomemacs/doomemacs/commit/b26980a4a4ee3853d0a811001d7ad45fa67d02a1) should fix that.

confirmed - working for me now.  Thanks so much.

**Comment by maikol-solis** [comment]
Hi @hlissner. We are almost there. Emacs starts normally, but these messages still appear: 

`doom doctor`

[cli.doom.241103204450.60078.log](https://github.com/user-attachments/files/17613270/cli.doom.241103204450.60078.log)

`emacs --debug-init`

```lisp 
Debugger entered--Lisp error: (void-variable Info-directory-list)
  (member "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list)
  (if (member "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list) Info-directory-list (setq Info-directory-list (cons "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list)))
  #f(lambda () [t] (if (member "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list) Info-directory-list (setq Info-directory-list (cons "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list))))()
  eval-after-load(latex #f(lambda () [t] (if (member "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list) Info-directory-list (setq Info-directory-list (cons "~/Library/TinyTeX/texmf-dist/doc/info" Info-directory-list)))))
  load-with-code-conversion("/Users/maikol/.doom.d/config.el" "/Users/maikol/.doom.d/config.el" t t)
  load("/Users/maikol/.doom.d/config" t nomessage)
  (condition-case e (load path noerror 'nomessage) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (setq path (locate-file path load-path (get-load-suffixes))) (if (not (and path (featurep 'doom))) (signal (car e) (cdr e)) (cl-loop for (err . dir) in (list (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir)) (cons 'doom-core-error doom-core-dir) (cons 'doom-user-error doom-user-dir) (cons 'doom-profile-error doom-profile-dir) (cons 'doom-module-error doom-modules-dir)) if (file-in-directory-p path dir) do (signal err (list (file-relative-name path (expand-file-name "../" dir)) e))))))
  doom-load("/Users/maikol/.doom.d/config" t)
  doom--startup-modules()
  doom-startup()
  (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup))
  (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))
  (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup))))
  (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda (s) (prin1-to-string s t)) (cdr error) ", ")) :warning) (setq init-file-had-error t)))
  (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name (doom-profile-init-file doom-profile))) (setq user-init-file (concat (string-remove-suffix ".elc" init-file-name) ".el")) (setq load-history (delete (assoc init-file-name load-history) load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'(lambda ... ...) (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error))))
  (let ((debug-on-error-from-init-file nil) (debug-on-error-should-be-set nil) (debug-on-error-initial (if (eq init-file-debug t) 'startup init-file-debug)) (inhibit-null-byte-detection t)) (let ((debug-on-error debug-on-error-initial)) (condition-case error (if init-file-user (progn (let ((init-file-name ...)) (setq user-init-file (concat ... ".el")) (setq load-history (delete ... load-history)) (doom-startup)))) ((debug error) (display-warning 'initialization (format-message "An error occurred while booting Doom Emacs:\n\n%s%s%s\n\nTo ensure normal operation, you should investigate and remove the\ncause of the error in your Doom config files. Start Emacs with\nthe `--debug-init' option to view a complete error backtrace." (get (car error) 'error-message) (if (cdr error) ": " "") (mapconcat #'... (cdr error) ", ")) :warning) (setq init-file-had-error t))) (or (eq debug-on-error debug-on-error-initial) (progn (setq debug-on-error-should-be-set t) (setq debug-on-error-from-init-file debug-on-error)))) (if debug-on-error-should-be-set (progn (setq debug-on-error debug-on-error-from-init-file))))
  startup--load-user-init-file@init-doom(#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t)
  apply(startup--load-user-init-file@init-doom (#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t))
  #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom)))(#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t)
  apply(#f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) (#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t))
  #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files)))(#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t)
  apply(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) (#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t))
  (unwind-protect (apply fn args) (progn (set-default 'inhibit-message nil)) (advice-remove #'tool-bar-setup #'ignore) (let ((sym 'tool-bar-mode)) (defalias 'doom-transient-hook5 #'(lambda (&rest _) "Transient hook for tool-bar-mode" (tool-bar-setup) (let ((sym ...)) (cond (... ...) (... ...))) (unintern 'doom-transient-hook5 nil))) (cond ((functionp sym) (advice-add 'tool-bar-mode :before #'doom-transient-hook5)) ((symbolp sym) (put 'doom-transient-hook5 'permanent-local-hook t) (add-hook sym #'doom-transient-hook5 nil)))) (if (default-toplevel-value 'mode-line-format) nil (progn (set-default 'mode-line-format (get 'mode-line-format 'initial-value)))))
  startup--load-user-init-file@undo-hacks(#f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) #f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t)
  apply(startup--load-user-init-file@undo-hacks #f(advice startup--load-user-init-file@load-site-files :before #f(advice startup--load-user-init-file@init-doom :override #<subr startup--load-user-init-file> ((depth . 100) (name . init-doom))) ((depth . 100) (name . load-site-files))) (#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t))
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x427de94ef70e71b>) #f(compiled-function () #<bytecode 0x731968ef8c4599b>) t)
  command-line()
  normal-top-level()
```

**Comment by hlissner** [comment]
@maikol-solis That one looks like it's coming from your `$DOOMDIR/config.el`. Do you have a `(after! latex ...)` or `(eval-with-load ...)` block in there where you reference `Info-directory-list`?

**Comment by maikol-solis** [comment]
@hlissner Yes, I have this chunk in my config 

```lisp 
(after! latex
  (add-to-list 'Info-directory-list "~/Library/TinyTeX/texmf-dist/doc/info"))
```

I have to remove it?

**Comment by maikol-solis** [comment]
Removing these lines makes doom start cleanly again.

**Comment by hlissner** [comment]
My bad; the issue required a more in-depth fix, which I've finally implemented in 7531c42. That should fix that error you saw (you shouldn't have to remove those lines, anyway).

**Comment by maikol-solis** [comment]
This commit fixed the remaining messages. Thanks for all, Henrik.
