### ISSUE TITLE
Help link in documentation leads to 404

### ISSUE THREAD

**Issue by raingloom** [doomemacs/doomemacs#8195]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Help link should go to a page that exists.

### Current behavior

I get a 404 page from Nginx.

### Steps to reproduce

- Open https://docs.doomemacs.org/latest/faq
- click help
  - links to https://docs.doomemacs.org/v21/#/developers/conventions/docs
- get shown an error page

### System Information

irrelevant

**Comment by hlissner** [comment]
I'm aware of this and other issues with https://docs.doomemacs.org. Please refrain from reporting more bugs about it, since they'll be addressed in one go once v3 goes live.

**Comment by dhasial** [comment]
I'm still getting this issue today. I was going to suggest some fixes to the documentation on folding, but yeah, 404.
