### ISSUE TITLE
good-scroll causes issue with ledger

### ISSUE THREAD

**Issue by mateoinc** [doomemacs/doomemacs#8376]
### What did you expect to happen?

In `ledger-mode`, when I call `ledger-add-transaction` and write the name of a previous transaction I expect to add a copy of that transaction (or its latest version) with the current date to my ledger. 

### What actually happened?

Since I've enabled `:ui (smooth-scroll +interpolate)` passing any name of a past transaction to `ledger-add-transaction` causes an error in the form of `good-scroll--advice-line-move: Args out of range: 125486, 1, 93` but with different numbers. Just chooring a date without a transaction name works normally. EDIT: Forgot to mention that this often starts failing from the second time I add a transaction, the first doesn't seem to have issues.

### Describe your attempts to resolve the issue

If I disable good-scroll with `good-scroll-mode` it works normally again.

### Steps to reproduce

1. Open a file with `ledger-mode` or use `org-edit-special` in an org file (I've tried both)
2. `SPC m a` (`ledger-add-transaction`)
3. Write the name of an existing transaction

### Package commit

ca7e226e1305ed7f10762315ad48f19c330cdd72

### System Information

Emacs 30.1 (compiled with "--with-modules --with-xft --with-cairo --with-compress-install --with-toolkit-scroll-bars --with-native-compilation --with-tree-sitter --with-json --with-x-toolkit=lucid 'CFALGS=-02 -pipe -march=native -fomit-frame-pointer' --with-imagemagick --disable-gc-mark-trace") on PopOS 22.04

**Comment by hlissner** [comment]
I suspect this is an upstream issue, but please produce [a backtrace](discourse.doomemacs.org/how2backtrace) from the error.

**Comment by mateoinc** [comment]
> I suspect this is an upstream issue, but please produce [a backtrace](discourse.doomemacs.org/how2backtrace) from the error.
```
Debugger entered--Lisp error: (args-out-of-range 87974 1 93)
  good-scroll--point-at-top-p()
  good-scroll--advice-line-move(#<subr line-move> 1 t)
  apply(good-scroll--advice-line-move #<subr line-move> (1 t))
  line-move(1 t)
  move-end-of-line(1)
  ledger-post-align-postings(1 93)
  ledger-add-transaction("2025/05/05 carrito" nil)
  funcall-interactively(ledger-add-transaction "2025/05/05 carrito" nil)
  command-execute(ledger-add-transaction)
```
The first number after `args-out-of-range` seems to change sometimes.

**Comment by hlissner** [comment]
I'm unable to reproduce this issue, but it seems the issue is with `good-scroll--point-at-top-p` not guarding against out-of-bounds errors, and should be reported upstream to address.

In the meantime, see if this workaround fixes the error for you:

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! good-scroll--point-at-top-fix-a ()
  "Return non-nil if the point is close to the top of the selected window."
  :override #'good-scroll--point-at-top-fix-a
  (save-restriction
    ;; Widen in case the window start is outside the visible part of the buffer
    (widen)
    (<= (line-number-at-pos (max (point) (point-min)) t)
        (1+ (line-number-at-pos (min (window-start) (point-max)) t)))))
```

**Comment by mateoinc** [comment]
Adding that causes problems with vertico it seems?
```Error in post-command-hook (vertico--exhibit): (excessive-lisp-nesting 1601)```
(couldn't get a backtrace, it only happens with M-x)
While the error in ledger is still the same.

**Comment by hlissner** [comment]
Oops, I forgot to rename the advice. I've fixed my original snippet above.

**Comment by hlissner** [comment]
I've pushed a local fix in aa6f390, but this should be reported/addressed upstream, so the wider Emacs community can benefit from it. In any case, thanks for bringing it to my attention!

**Comment by mateoinc** [comment]
Hey sorry I didn't reply earlier. No excuse, just distracted with life. Thing is, this doesn't fix it for me, I still get this after a doom upgrade
```
Debugger entered--Lisp error: (args-out-of-range 96347 1 96)
  good-scroll--point-at-top-p()
  good-scroll--advice-line-move(#<subr line-move> 1 t)
  apply(good-scroll--advice-line-move #<subr line-move> (1 t))
  line-move(1 t)
  move-end-of-line(1)
  ledger-post-align-postings(1 96)
  ledger-add-transaction("2025/06/02 test" nil)
  funcall-interactively(ledger-add-transaction "2025/06/02 test" nil)
  command-execute(ledger-add-transaction)
```

**Comment by hlissner** [comment]
My bad. Just realized a typo in aa6f390. As of 313e8fb this should be fixed.

**Comment by mateoinc** [comment]
Works now, thanks!
