### ISSUE TITLE
install doomemacs error when clone centered-window-mode

### ISSUE THREAD

**Issue by sincebyte** [doomemacs/doomemacs#8512]
### I confirm that...

- [x] I searched the issue tracker and found no similar issues.

- [x] I searched the [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [discussion board](https://doomemacs.org/discuss), and [Google](https://google.com) for solutions to my issue.

- [x] I read [the debugging guide](https://doomemacs.org/d/how2debug) and researched the issue to the best of my ability.

- [x] My issue can be observed on the latest available commit of Doom.

- [x] My issue can be observed on a stable release of Emacs (i.e. doesn't end in `.50`, `.60`, or `.90`–`.99`)

### Describe your issue

when exec doom install 
```
 > Cloning centered-window-mode (for centered-window)...
 There was an unexpected runtime error
      Message: Wrong type argument
      Details: (stringp nil)
      Backtrace:
        (call-process "git" nil (t "/var/folders/rk/jnpjr40132bgv0fvvgh_wbhr...
        (apply call-process "git" nil (t "/var/folders/rk/jnpjr40132bgv0fvvg...
        (list (apply #'call-process program nil (list t straight--process-st...
        (progn (list (apply #'call-process program nil (list t straight--pro...
        (unwind-protect (progn (list (apply #'call-process program nil (list...
        (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn...
        (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current...
        (if straight-display-subprocess-prompts (apply #'straight--process-c...
        (#[(program &rest args) ((if (string-match-p "/" program) (progn (se...
        (apply #[(program &rest args) ((if (string-match-p "/" program) (pro...
        (let ((process-environment (copy-sequence process-environment))) (se...
        (doom-straight--ignore-gitconfig-a #[(program &rest args) ((if (stri...
```

### Steps to reproduce

1. clone doomemacs
2. install doomemacs

### System information
https://pastebin.com/fP8bUG41
```
generated  Sep 18, 2025 14:48:11
system     MacOS 26.0 Darwin 25.0.0 arm64
emacs      31.0.50 EMACSDIR=~/.config/emacs/
	   EMACS=/Applications/emacs.app/Contents/MacOS/Emacs
doom       3.0.0-pre PROFILE=_default@0 HEAD 6a270b64d 2025-09-16 11:03:42 -0400
	   ~/.doom.d/
shell      /opt/homebrew/bin/fish
features   ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG LCMS2 LIBXML2 MODULES
	   NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF
	   TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM ZLIB
traits     batch envvar-file custom-file
custom     connection-local-criteria-alist connection-local-profile-alist
modules    :config use-package :completion corfu (vertico +icons) :ui doom
	   doom-dashboard hl-todo indent-guides modeline ophints (popup
	   +defaults) (vc-gutter +pretty) vi-tilde-fringe workspaces :editor
	   (evil +everywhere) file-templates fold (format +onsave) snippets
	   :emacs (dired +icons +dirvish) electric (undo +tree) vc :term vterm
	   :checkers syntax :tools (eval +overlay) lookup lsp magit tree-sitter
	   :os macos :lang (cc +lsp) emacs-lisp (go +lsp) (java +lsp
	   +tree-sitter) (javascript +lsp) markdown (org +roam2 +present)
	   (python +lsp +pyright +tree-sitter) rest (rust +lsp) sh (web +lsp)
	   yaml :app emms :neo-emacs (&user java) (&user shell) (&user common)
	   (&user org) (&user rime) (&user translate) (&user find) (&user sql)
	   (&user modelinexp) (&user elfeed) (&user alpha) (&user git) (&user
	   telega) :config (default +bindings +smartparens)
packages   (org-appear) (org-roam-ui) (rime) (liberime) (gt) (d2-mode) (gnuplot)
	   (string-inflection) (ejc-sql) (kaolin-themes) (company-posframe)
	   (xml-format) (elfeed) (eredis) (org-modern) (yaml-mode)
	   (docker-compose-mode) (magit-delta) (gptel) (telega) (undo-tree)
	   (transwin) (pdf-tools) (ef-themes) (verb) (focus) (ialign)
	   (powerline) (kind-icon) (rainbow-delimiters) (uniline)
	   (color-theme-sanityinc-tomorrow) (keyfreq :recipe (:host github :repo
	   dacap/keyfreq)) (awesome-tray :recipe (:host github :repo
	   manateelazycat/awesome-tray :branch master)) (bookmark+ :recipe
	   (:host github :repo emacsmirror/bookmark-plus :branch master)) (emt
	   :recipe (:host github :repo roife/emt :branch master))
	   (pulsing-cursor :recipe (:host github :repo
	   jasonjckn/pulsing-cursor)) (transient :pin
	   aa32e0d66cc389befed7a8e8df9439d92a729daa) (lsp-mode :pin
	   c10b9066857d26a99fca1cb336d9be341ef3e09f)
unpin      restclient restclient-jq npm-mode lsp-java lsp-mode dirvish apheleia
```

**Comment by hlissner** [comment]
Please include the backtrace error file and the output of the `doom info` shell command.

**Comment by sincebyte** [comment]
> Please include the backtrace error file and the output of the `doom info` shell command.

already here

**Comment by sincebyte** [comment]
```
 ("centered-window-mode"
    . "80965f6c6afe8d918481433984b493de72af5399")
```
It seems that the commit of 80965 is not exist.

**Comment by sincebyte** [comment]
I disabled the org +present the bug disappeared

**Comment by marienz** [comment]
`:lang org +present` [pulls in](https://github.com/doomemacs/doomemacs/blob/f3b4314ddaf8f7253283f4bb001432fab8459f00/modules/lang/org/packages.el#L90-L93) https://github.com/anler/centered-window-mode, which seems to have disappeared.

straight does not seem to handle this particularly well:

- When not using snapshots (`straight-vc-use-snapshot-installation` set to nil), I get a crash like @sincebyte does ([cli.doom.250918203843.25928.error.log](https://github.com/user-attachments/files/22404498/cli.doom.250918203843.25928.error.log)). strace shows straight runs `git remote show origin` (with the url for "origin" being https://github.com/anler/centered-window-mode), which fails (interactively it asks for auth): it looks like it then crashes invoking git with `("branch" "-m" nil)` (having failed to determine which branch it wants). I haven't tracked down whether that's a pure straight.el bug or not.
- When using snapshots (leave `straight-vc-use-snapshot-installation` alone and start from an empty DOOMLOCALDIR), straight silently fails to fetch and install centered-window-mode: after `doom sync`, `$DOOMLOCALDIR/build-30.2/centered-window` is an empty directory. Because Doom's use of centered-window-mode is [guarded by `fboundp`](https://github.com/doomemacs/doomemacs/blob/395a807aae955c47fe00fab79120ec3f20da1e4e/modules/lang/org/autoload/contrib-present.el#L63), this probably works (with some loss of functionality). I'm not entirely sure how straight manages this: it looks like it [uses `url-retrieve-synchronously` followed by running `tar`](https://github.com/radian-software/straight.el/blob/0ad6fd8f37bd918c72989df18c76a68649f0a372/straight.el#L3081-L3090), but although I can see how it would miss the 404 in the first step I don't understand how the tar succeeds... `wget --content-on-error https://github.com/anler/centered-window-mode/archive/80965f6c6afe8d918481433984b493de72af5399.tar.gz` gets me a file containing the text "Not Found", both that and an empty file make `tar -zxf` fail, so I'm missing something there.

[doom-info.txt](https://github.com/user-attachments/files/22404568/doom-info.txt)

**Comment by marienz** [comment]
(@sincebyte can you please reopen this if you're still seeing it with `org +present` enabled? I shouldn't file a duplicate and do not have permission to reopen this issue...)

**Comment by hlissner** [comment]
As of 9debe1b this should be resolved (now using emacsmirror/centered-window instead). Thanks for bringing it to my attention!

**Comment by h35514n** [comment]
In case anyone else runs into this: Deleting or modifying `doomemacs/.local/straight/repos/melpa/recipes/centered-window` may also be necessary.

<details>
<summary>debugging details</summary>

### Steps to Reproduce

I'm seeing `doom upgrade` continue to run into this bug even after all of the following remediation steps have been taken:

1. Pull latest `doomemacs` `master`, verify `9debe1b` is present
2. Manually delete `centered-window` directory in `.local/straight/repos`
3. Manually delete `centered-window` directory in `.local/straight/build-30.2`
4. Manually delete `.local/straight/build-30.2-cache.el`

```text

straight master % git show 9debe1b
commit 9debe1b3fc62ed62e40243871dfb7c70b75ffdf8

    bump: centered-window

    anler/centered-window-mode@80965f6c6afe -> emacsmirror/centered-window@80965f6c6afe

    anler/centered-window-mode has vanished, causing errors when installed
    with ':lang (org +present)'.

    Fix: #8512

straight master % rm -rf build-30.2-cache.el build-30.2/centered-window repos/centered-window

straight master % doom upgrade
[...]
    > Updating recipe repos...
    > Cloning centered-window-mode (for centered-window)...
    x The package manager threw an error
    x Last 16 lines of straight's error log:
      $ git merge-base --is-ancestor origin/master master
      [Return code: 0]
      $ cd ~/.dotfiles/share/doomemacs/.local/straight/repos/emacsmirror-mirror/
      $ git rev-parse HEAD
      81da178dc8b1cfad2e6704f7dce6370ab679ec39
      [Return code: 0]
      $ cd ~/.dotfiles/share/doomemacs/.local/straight/repos/
      $ git clone --origin origin --no-checkout https\://github.com/anler/centered-window-mode.git ~/.dotfiles/share/doomemacs/.local/straight/repos/centered-window-mode/ --depth 1 --single-branch --no-tags
      Cloning into '~/.dotfiles/share/doomemacs/.local/straight/repos/centered-window-mode'...
      fatal: could not read Username for 'https://github.com': Device not configured
      [Return code: 128]
      $ cd ~/.dotfiles/share/doomemacs/.local/straight/repos/
      $ git clone --origin origin --no-checkout https\://github.com/anler/centered-window-mode.git ~/.dotfiles/share/doomemacs/.local/straight/repos/centered-window-mode/ --no-single-branch
      Cloning into '~/.dotfiles/share/doomemacs/.local/straight/repos/centered-window-mode'...
      fatal: could not read Username for 'https://github.com': Device not configured
      [Return code: 128]
    ! Wrote extended straight log to ~/.dotfiles/share/doomemacs/.local/state/logs/cli.doom.250920080016.28501.error

```

### Resolution

```
.local master % rm  straight/repos/melpa/recipes/centered-window

.local master % doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
[...]
  > Ensuring packages are installed and built...
    > Updating recipe repos...
      > Repository "melpa" has a dirty worktree:

         D recipes/centered-window

           1) Abort
           2) Stash changes
           3) Discard changes (Choose this if unsure)

        How to proceed? (1, 2, 3; don't know? Pick 3) 3
        Discard all local changes permanently? (y or n) y
    > Cloning centered-window...csmirror-mirror...
    > Building centered-window...
[...]
    ✓ Built init.30.2.el
  - Restart Emacs for changes to take effect
✓ Finished in 4m 13s

```
</details>

**Comment by bestlem** [comment]
As in https://github.com/orgs/doomemacs/discussions/44 I think the issue is still there.

I note the URL was updated but the :pin was not

**Comment by marienz** [comment]
(I still had a cached copy of the original repo around, so I did a bit of git archeology:

- Melpa got repointed at https://github.com/nullvec/centered-window-mode (see https://github.com/melpa/melpa/commit/2dbcb69f603a94b6abc196d45ec5d2fb2ddc1344), and the one commit there (701f56cd1d2b68352d29914f05ca1b0037bb2595) is the same code as the 80965f6c6afe8d918481433984b493de72af5399 commit Doom was using, with minor differences to URLs in README and comments and the like.
- GitHub says the emacsmirror version is "forked from larstvei/centered-window-mode", which isn't exactly true in the git sense of the word: it's "1 commit ahead" / "14 commits behind", which is the total number of commits in the nullvec and larstvei repository respectively. Those repositories do not share git history, but the current head commit in the larstvei repo (28b04afa606b0cebc3265e2aa4616e224368d542) is an earlier commit in the repo Doom was using before all this.

So updating to 701f56cd1d2b68352d29914f05ca1b0037bb2595 (from either emacsmirror or nullvec) looks reasonable, it looks like that's where the most up-to-date version of this package now lives.)

**Comment by hlissner** [comment]
As of ef9e8d8 I've switched to the nullvec/centered-window-mode source, which should resolve this. Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!

**Comment by bestlem** [comment]
Seems OK for me

**Comment by Themood** [comment]
Doom docs still points to the old gh repo for this package
